### ISSUE TITLE
Issue with the project running

### ISSUE THREAD

**Issue by 20481A5450** [tonykipkemboi/ollama_streamlit_demos#1]
First of all great work by the way @tonykipkemboi , it got my attention as i'm a student and i do work with llm's to complete my project works in time and this initiative project got  my attention.

###  Issue
Coming back to the issue While i was trying to run the file with the command 
```bash 
streamlit run 01_💬_Chat_Demo.py
```
I'm facing an error 
![Screenshot 2024-04-21 110353](https://github.com/tonykipkemboi/ollama_streamlit_demos/assets/99806742/1185e5b7-4937-42fa-bd32-26be28a67707)

I'm currently running on python version : 3.11.5
and i have gone through each and every installation step.

**Comment by tonykipkemboi** [comment]
Hi @20481A5450, thank you. Can you confirm you're running the command above in the same directory that the `01_💬_Chat_Demo.py` is in?

**Comment by 20481A5450** [comment]
Yes I'm running in the same directory.
Thanks for your message @tonykipkemboi  The issue got resolve streamlit is running right now.
I have restarted my system, the issue may be in loading the packages once i restart tIhe system it worked as usual.
I'm looking for open source contributions let me know if you have anything in mind.
Thank you
